services:

  # Database
  dev-db:
    image: postgres:latest
    container_name: video-streaming-db
    volumes:
      - postgres-db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5430:5432" # host port : internal service port
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - backend-network
      - app-network

  # redis
  redis:
    hostname: redis
    restart: unless-stopped
    image: redis:8.0-M02-alpine
    ports:
      - "6379:6379"
    networks:
      - redis-network

  # Web server
  web:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: video-streaming-backend
    restart: unless-stopped
    command: sh ./run_web.sh
    volumes:
      - .:/app
      - ~/nfs_shared_storage:/mnt/shared_storage
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - WEB_HOST=${WEB_HOST}
      - WEB_PORT=${WEB_PORT}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      - CELERY_RESULT_BACKEND=redis://${REDIS_HOST}:${REDIS_PORT}/1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
    networks:
      - backend-network
      - app-network
      - redis-network  # Connect the web service to both networks
    depends_on:
      - dev-db

  nginx:
    image: nginx:1.23-alpine
    ports:
      - "80:80" # External port 80 to internal port 80 of nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the custom Nginx config file into docker
      - ~/nfs_shared_storage:/app/media # Mount the NFS media files into NGINX
      - static_volume:/app/static  # Mount the static files into NGINX
    depends_on:
      - web
    networks:
      - app-network

  # Celery worker
  worker1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
    command: sh ./run_celery.sh
    volumes:
      - .:/app
      - ~/nfs_shared_storage:/mnt/shared_storage
    networks:
      - backend-network
      - worker-network
      - redis-network # Connect the worker to both networks

  worker2:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
    command: sh ./run_celery.sh
    volumes:
      - .:/app
      - ~/nfs_shared_storage:/mnt/shared_storage
    networks:
      - backend-network
      - worker-network
      - redis-network # Connect the worker to both networks


networks:
  backend-network:

  app-network:

  worker-network:

  redis-network:

  flower-network:

volumes:
  postgres-db:
  static_volume: