services:

  # Web server
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: video-streaming-backend
    restart: unless-stopped
    command: sh ./run_web.sh
    volumes:
      - .:/app
      - ./media:/app/media
      - static_volume:/app/static
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - WEB_HOST=${WEB_HOST}
      - WEB_PORT=${WEB_PORT}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - CELERY_BROKER_URL=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
      - CELERY_RESULT_BACKEND=redis://${REDIS_HOST}:${REDIS_PORT}/0
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}

volumes:
  static_volume: