services:

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "5673:5672"
      - "15672:15672"
    networks:
      - app-network

  # Web server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: sh ./run_web.prod.sh
    volumes:
      - media_volume:/app/media
      - static_volume:/app/static
    ports:
      - "8000-8002:8000"
    deploy:
      replicas: 3
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
    networks:
      - app-network

  # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - CELERY_BROKER_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}
    command: sh ./run_celery.sh
    volumes:
      - .:/app
    depends_on:
      - rabbit
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # External port 80 to internal port 80 of nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the custom Nginx config file into docker
      - static_volume:/app/static  # Mount the static files into NGINX
      - media_volume:/app/media # Mount the media files into NGINX
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:

volumes:
  static_volume:
  media_volume: