# Generated by Django 5.0.6 on 2024-07-15 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user',
            new_name='author',
        ),
    ]
