# Generated by Django 5.0.6 on 2024-06-29 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosegment',
            name='created_at',
        ),
    ]
