# Generated by Django 5.0.6 on 2024-08-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_video', '0003_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='mpd_file_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
