# Generated by Django 5.0.6 on 2024-06-29 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_video', '0003_alter_video_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='id',
            new_name='uuid',
        ),
    ]
