# Generated by Django 5.0.6 on 2024-07-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_video', '0004_rename_id_video_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='mpd_file_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
