# Generated by Django 5.0.6 on 2025-01-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_video', '0005_laststreamedsegment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laststreamedsegment',
            name='last_segment',
        ),
    ]
