# Generated by Django 5.0.6 on 2024-07-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_video', '0005_alter_video_mpd_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
