# Generated by Django 5.0.6 on 2025-01-05 08:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_video', '0006_remove_laststreamedsegment_last_segment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastStreamedSegment',
            new_name='LastStreamedPoint',
        ),
    ]
