# Generated by Django 5.0.6 on 2025-01-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_video', '0007_rename_laststreamedsegment_laststreamedpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='laststreamedpoint',
            name='last_played_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
