# Generated by Django 5.0.6 on 2025-01-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_video', '0008_laststreamedpoint_last_played_seconds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laststreamedpoint',
            old_name='last_played_seconds',
            new_name='last_played_second',
        ),
    ]
