# Generated by Django 5.0.6 on 2025-01-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_video', '0009_rename_last_played_seconds_laststreamedpoint_last_played_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
